In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_validate
from sklearn.metrics import accuracy_score

In [10]:
df = pd.read_csv('/Users/ayushmishra06/Documents/key_key_3/src/biometria_trained.csv')

In [11]:
df.head()

,t_T1,th_F1,h_T2,he_F2,e_T3,e _F3,_T4,q_F4,q_T5,qu_F5,...,k_T45,k _F45,_T46,d_F46,d_T47,do_F47,o_T48,og_F48,g_T49,CLASS
0,0.002,0.084,0.001,0.083,0.000,0.212,0.001,0.537,0.001,0.190,...,0.001,0.217,0.001,0.630,0.001,0.133,0.002,0.602,0.002,69e5f2471e0218e82d25aaab
1,0.002,0.088,0.001,0.075,0.001,0.173,0.001,0.509,0.002,0.239,...,0.001,0.103,0.001,0.499,0.002,0.177,0.001,0.444,0.001,69e5f2471e0218e82d25aaab
2,0.002,0.099,0.001,0.067,0.001,0.187,0.001,0.549,0.001,0.111,...,0.001,0.159,0.001,1.196,0.001,0.090,0.001,0.275,0.001,69e5f2471e0218e82d25aaab
3,0.002,0.108,0.001,0.098,0.001,0.152,0.001,0.369,0.002,0.149,...,0.001,0.212,0.001,0.796,0.001,0.087,0.000,0.273,0.002,69e5f2471e0218e82d25aaab
4,0.001,0.069,0.001,0.079,0.001,0.161,0.001,0.283,0.002,0.165,...,0.001,0.171,0.002,0.299,0.001,0.126,0.001,0.334,0.001,69e5f2471e0218e82d25aaab

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 98 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   t_T1    61 non-null     float64
 1   th_F1   61 non-null     float64
 2   h_T2    61 non-null     float64
 3   he_F2   61 non-null     float64
 4   e_T3    61 non-null     float64
 5   e _F3   61 non-null     float64
 6    _T4    61 non-null     float64
 7    q_F4   61 non-null     float64
 8   q_T5    61 non-null     float64
 9   qu_F5   61 non-null     float64
 10  u_T6    61 non-null     float64
 11  ui_F6   61 non-null     float64
 12  i_T7    61 non-null     float64
 13  ic_F7   61 non-null     float64
 14  c_T8    61 non-null     float64
 15  ck_F8   61 non-null     float64
 16  k_T9    61 non-null     float64
 17  k _F9   61 non-null     float64
 18   _T10   61 non-null     float64
 19   b_F10  61 non-null     float64
 20  b_T11   61 non-null     float64
 21  br_F11  61 non-null     float64
 22  r_T12   61 non-null     float64
 23  ro_F12  61 non-null     float64
 24  o_T13   61 non-null     float64
 25  ow_F13  61 non-null     float64
 26  w_T14   61 non-null     float64
 27  wn_F14  61 non-null     float64
 28  n_T15   61 non-null     float64
 29  n _F15  61 non-null     float64
 30   _T16   61 non-null     float64
 31   f_F16  61 non-null     float64
 32  f_T17   61 non-null     float64
 33  fo_F17  61 non-null     float64
 34  o_T18   61 non-null     float64
 35  ox_F18  61 non-null     float64
 36  x_T19   61 non-null     float64
 37  x _F19  61 non-null     float64
 38   _T20   61 non-null     float64
 39   j_F20  61 non-null     float64
 40  j_T21   61 non-null     float64
 41  ju_F21  61 non-null     float64
 42  u_T22   61 non-null     float64
 43  um_F22  61 non-null     float64
 44  m_T23   61 non-null     float64
 45  mp_F23  61 non-null     float64
 46  p_T24   61 non-null     float64
 47  ps_F24  61 non-null     float64
 48  s_T25   61 non-null     float64
 49  s _F25  61 non-null     float64
 50   _T26   61 non-null     float64
 51   o_F26  61 non-null     float64
 52  o_T27   61 non-null     float64
 53  ov_F27  61 non-null     float64
 54  v_T28   61 non-null     float64
 55  ve_F28  61 non-null     float64
 56  e_T29   61 non-null     float64
 57  er_F29  61 non-null     float64
 58  r_T30   61 non-null     float64
 59  r _F30  61 non-null     float64
 60   _T31   61 non-null     float64
 61   t_F31  61 non-null     float64
 62  t_T32   61 non-null     float64
 63  th_F32  61 non-null     float64
 64  h_T33   61 non-null     float64
 65  he_F33  61 non-null     float64
 66  e_T34   61 non-null     float64
 67  e _F34  61 non-null     float64
 68   _T35   61 non-null     float64
 69   l_F35  61 non-null     float64
 70  l_T36   61 non-null     float64
 71  la_F36  61 non-null     float64
 72  a_T37   61 non-null     float64
 73  az_F37  61 non-null     float64
 74  z_T38   61 non-null     float64
 75  zy_F38  61 non-null     float64
 76  y_T39   61 non-null     float64
 77  y _F39  61 non-null     float64
 78   _T40   61 non-null     float64
 79   b_F40  61 non-null     float64
 80  b_T41   61 non-null     float64
 81  bl_F41  61 non-null     float64
 82  l_T42   61 non-null     float64
 83  la_F42  61 non-null     float64
 84  a_T43   61 non-null     float64
 85  ac_F43  61 non-null     float64
 86  c_T44   61 non-null     float64
 87  ck_F44  61 non-null     float64
 88  k_T45   61 non-null     float64
 89  k _F45  61 non-null     float64
 90   _T46   61 non-null     float64
 91   d_F46  61 non-null     float64
 92  d_T47   61 non-null     float64
 93  do_F47  61 non-null     float64
 94  o_T48   61 non-null     float64
 95  og_F48  61 non-null     float64
 96  g_T49   61 non-null     float64
 97  CLASS   61 non-null     object
dtypes: float64(97), object(1)
memory usage: 46.8+ KB

In [13]:
df.shape

(61, 98)

In [14]:
df.describe()

,t_T1,th_F1,h_T2,he_F2,e_T3,e _F3,_T4,q_F4,q_T5,qu_F5,...,ck_F44,k_T45,k _F45,_T46,d_F46,d_T47,do_F47,o_T48,og_F48,g_T49
count,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,...,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000
mean,0.001328,0.203574,0.000803,0.213328,0.000820,0.246672,0.000803,0.457820,0.001000,0.235262,...,0.202672,0.000803,0.239426,0.000869,0.571443,0.000885,0.216492,0.000689,0.414492,0.001000
std,0.000676,0.138767,0.000542,0.131050,0.000466,0.137197,0.000440,0.178962,0.000483,0.098571,...,0.146594,0.000401,0.098713,0.000562,0.226340,0.000486,0.130009,0.000501,0.230875,0.000548
min,0.000000,0.037000,0.000000,0.045000,0.000000,0.055000,0.000000,0.120000,0.000000,0.111000,...,0.060000,0.000000,0.073000,0.000000,0.179000,0.000000,0.064000,0.000000,0.195000,0.000000
25%,0.001000,0.099000,0.000000,0.135000,0.001000,0.163000,0.001000,0.319000,0.001000,0.165000,...,0.134000,0.001000,0.171000,0.001000,0.391000,0.001000,0.126000,0.000000,0.252000,0.001000
50%,0.001000,0.149000,0.001000,0.191000,0.001000,0.194000,0.001000,0.467000,0.001000,0.220000,...,0.169000,0.001000,0.220000,0.001000,0.563000,0.001000,0.189000,0.001000,0.336000,0.001000
75%,0.002000,0.271000,0.001000,0.249000,0.001000,0.287000,0.001000,0.602000,0.001000,0.286000,...,0.234000,0.001000,0.297000,0.001000,0.731000,0.001000,0.249000,0.001000,0.502000,0.001000
max,0.003000,0.658000,0.002000,0.666000,0.002000,0.698000,0.002000,0.826000,0.002000,0.663000,...,1.141000,0.001000,0.528000,0.002000,1.196000,0.002000,0.782000,0.002000,1.332000,0.002000

In [15]:
data = df.iloc[:,0:97]
target = df['CLASS']

In [18]:
data.head()

,t_T1,th_F1,h_T2,he_F2,e_T3,e _F3,_T4,q_F4,q_T5,qu_F5,...,ck_F44,k_T45,k _F45,_T46,d_F46,d_T47,do_F47,o_T48,og_F48,g_T49
0,0.002,0.084,0.001,0.083,0.000,0.212,0.001,0.537,0.001,0.190,...,0.420,0.001,0.217,0.001,0.630,0.001,0.133,0.002,0.602,0.002
1,0.002,0.088,0.001,0.075,0.001,0.173,0.001,0.509,0.002,0.239,...,0.146,0.001,0.103,0.001,0.499,0.002,0.177,0.001,0.444,0.001
2,0.002,0.099,0.001,0.067,0.001,0.187,0.001,0.549,0.001,0.111,...,0.133,0.001,0.159,0.001,1.196,0.001,0.090,0.001,0.275,0.001
3,0.002,0.108,0.001,0.098,0.001,0.152,0.001,0.369,0.002,0.149,...,0.192,0.001,0.212,0.001,0.796,0.001,0.087,0.000,0.273,0.002
4,0.001,0.069,0.001,0.079,0.001,0.161,0.001,0.283,0.002,0.165,...,0.165,0.001,0.171,0.002,0.299,0.001,0.126,0.001,0.334,0.001

In [19]:
target.head()

0    69e5f2471e0218e82d25aaab
1    69e5f2471e0218e82d25aaab
2    69e5f2471e0218e82d25aaab
3    69e5f2471e0218e82d25aaab
4    69e5f2471e0218e82d25aaab
Name: CLASS, dtype: object

In [20]:
data_train, data_test, target_train, target_test = train_test_split(data,target,test_size=0.2,random_state=10)

In [21]:
knn_model = KNeighborsClassifier(n_neighbors=3,metric='manhattan')
knn_model.fit(data_train,target_train)
prediction = knn_model.predict(data_test)

In [22]:
accuracy = accuracy_score(target_test, prediction)

In [23]:
accuracy

0.6153846153846154

In [24]:
scores = cross_validate(knn_model,data,target,scoring=['accuracy'])
scores

{'fit_time': array([0.00689697, 0.00128722, 0.00124526, 0.0018301 , 0.00126004]),
 'score_time': array([0.01430702, 0.00210571, 0.00200677, 0.00303078, 0.00200987]),
 'test_accuracy': array([0.38461538, 0.83333333, 0.58333333, 0.5       , 0.5       ])}

In [25]:
score_result = scores['test_accuracy'].mean() * 100
score_result

np.float64(56.02564102564103)

In [26]:
k_range = list(range(1, 10))
leaf_size = list(range(1, 50))
weight_options = ["uniform", "distance"]
p = [1, 2]

In [27]:
param_grid = dict(leaf_size=leaf_size, n_neighbors=k_range, weights=weight_options, p=p)

In [28]:
knn = KNeighborsClassifier()

In [29]:
grid = GridSearchCV(knn, param_grid, scoring='accuracy')
grid.fit(data, target)

best_score = grid.best_score_
best_params = grid.best_params_
best_estimator = grid.best_estimator_

print('[+] Best Score - ', best_score)
print('[+] Best Params - ', best_params)
print('[+] Best Estimator - ', best_estimator)

[+] Best Score -  0.6243589743589744
[+] Best Params -  {'leaf_size': 1, 'n_neighbors': 3, 'p': 1, 'weights': 'distance'}
[+] Best Estimator -  KNeighborsClassifier(leaf_size=1, n_neighbors=3, p=1, weights='distance')

In [46]:
sample = df.iloc[60, 0:97].tolist()
true_user_id = df.iloc[60]['CLASS']

In [47]:
sample_df = pd.DataFrame.transpose(pd.DataFrame(sample))

In [48]:
sample_df

,0,1,2,3,4,5,6,7,8,9,...,87,88,89,90,91,92,93,94,95,96
0,0.0,0.155,0.0,0.229,0.0,0.18,0.001,0.325,0.001,0.165,...,1.141,0.001,0.176,0.0,0.179,0.001,0.078,0.0,0.285,0.0

In [49]:
user_predict = knn_model.predict(sample_df)
print("User predict:", user_predict)
print("Real User ID:", true_user_id)

User predict: ['69e63288f7076b1625873135']
Real User ID: 69e63288f7076b1625873135

/Users/ayushmishra06/Documents/key_key_3/.venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [2]:
import pandas as pd
df1 = pd.read_csv("/Users/ayushmishra06/Documents/key_key_3/src/biometria_trained.csv")
df2 = pd.read_csv("/Users/ayushmishra06/Documents/key_key_3/src/ml-service/biometria.csv")

In [3]:
df1.head()

,t_T1,th_F1,h_T2,he_F2,e_T3,e _F3,_T4,q_F4,q_T5,qu_F5,...,k_T45,k _F45,_T46,d_F46,d_T47,do_F47,o_T48,og_F48,g_T49,CLASS
0,0.002,0.084,0.001,0.083,0.000,0.212,0.001,0.537,0.001,0.190,...,0.001,0.217,0.001,0.630,0.001,0.133,0.002,0.602,0.002,69e5f2471e0218e82d25aaab
1,0.002,0.088,0.001,0.075,0.001,0.173,0.001,0.509,0.002,0.239,...,0.001,0.103,0.001,0.499,0.002,0.177,0.001,0.444,0.001,69e5f2471e0218e82d25aaab
2,0.002,0.099,0.001,0.067,0.001,0.187,0.001,0.549,0.001,0.111,...,0.001,0.159,0.001,1.196,0.001,0.090,0.001,0.275,0.001,69e5f2471e0218e82d25aaab
3,0.002,0.108,0.001,0.098,0.001,0.152,0.001,0.369,0.002,0.149,...,0.001,0.212,0.001,0.796,0.001,0.087,0.000,0.273,0.002,69e5f2471e0218e82d25aaab
4,0.001,0.069,0.001,0.079,0.001,0.161,0.001,0.283,0.002,0.165,...,0.001,0.171,0.002,0.299,0.001,0.126,0.001,0.334,0.001,69e5f2471e0218e82d25aaab

In [4]:
df2.head()

,C_T1,CO_F1,O_T2,OM_F2,M_T3,Ms_F3,s_T4,sG_F4,G_T5,GR_F5,...,D_T48,DA_F48,A_T49,AD_F49,D_T50,DE_F50,E_T51,ES_F51,S_T51,CLASS
0,-0.115,-0.998,-0.131,-0.496,-0.102,-0.816,-0.064,-0.854,-0.088,-0.713,...,-0.115,-0.705,-0.138,-0.371,-0.100,-0.393,-0.108,-0.439,-0.070,3
1,-0.091,-0.493,-0.083,-0.461,-0.085,-0.404,-0.079,-0.429,-0.104,-0.349,...,-0.113,-0.345,-0.119,-0.345,-0.088,-0.349,-0.093,-0.384,-0.069,3
2,-0.092,-0.412,-0.128,-0.354,-0.074,-0.462,-0.072,-0.393,-0.092,-0.415,...,-0.145,-0.300,-0.080,-0.325,-0.120,-0.333,-0.108,-0.397,-0.076,3
3,-0.092,-0.317,-0.132,-0.341,-0.068,-0.328,-0.077,-0.352,-0.105,-0.215,...,-0.129,-0.321,-0.115,-0.237,-0.124,-0.300,-0.096,-0.341,-0.059,3
4,-0.087,-0.416,-0.101,-0.381,-0.103,-0.429,-0.080,-0.437,-0.116,-0.405,...,-0.116,-0.289,-0.080,-0.252,-0.096,-0.428,-0.084,-0.305,-0.060,3

In [5]:
df1.shape

(62, 98)

In [6]:
df2.shape

(100, 98)

In [9]:
print(df1.columns)
print(df2.columns)

Index(['t_T1', 'th_F1', 'h_T2', 'he_F2', 'e_T3', 'e _F3', ' _T4', ' q_F4',
       'q_T5', 'qu_F5', 'u_T6', 'ui_F6', 'i_T7', 'ic_F7', 'c_T8', 'ck_F8',
       'k_T9', 'k _F9', ' _T10', ' b_F10', 'b_T11', 'br_F11', 'r_T12',
       'ro_F12', 'o_T13', 'ow_F13', 'w_T14', 'wn_F14', 'n_T15', 'n _F15',
       ' _T16', ' f_F16', 'f_T17', 'fo_F17', 'o_T18', 'ox_F18', 'x_T19',
       'x _F19', ' _T20', ' j_F20', 'j_T21', 'ju_F21', 'u_T22', 'um_F22',
       'm_T23', 'mp_F23', 'p_T24', 'ps_F24', 's_T25', 's _F25', ' _T26',
       ' o_F26', 'o_T27', 'ov_F27', 'v_T28', 've_F28', 'e_T29', 'er_F29',
       'r_T30', 'r _F30', ' _T31', ' t_F31', 't_T32', 'th_F32', 'h_T33',
       'he_F33', 'e_T34', 'e _F34', ' _T35', ' l_F35', 'l_T36', 'la_F36',
       'a_T37', 'az_F37', 'z_T38', 'zy_F38', 'y_T39', 'y _F39', ' _T40',
       ' b_F40', 'b_T41', 'bl_F41', 'l_T42', 'la_F42', 'a_T43', 'ac_F43',
       'c_T44', 'ck_F44', 'k_T45', 'k _F45', ' _T46', ' d_F46', 'd_T47',
       'do_F47', 'o_T48', 'og_F48', 'g_T49', 'CLASS'],
      dtype='object')
Index(['C_T1', 'CO_F1', 'O_T2', 'OM_F2', 'M_T3', 'Ms_F3', 's_T4', 'sG_F4',
       'G_T5', 'GR_F5', 'R_T6', 'RA_F6', 'A_T7', 'AN_F7', 'N_T8', 'ND_F8',
       'D_T9', 'DE_F9', 'E_T10', 'ES_F10', 'S_T11', 'Ss_F11', 's_T12',
       'sP_F12', 'P_T13', 'PO_F13', 'O_T14', 'OD_F14', 'D_15', 'DE_F15',
       'E_T16', 'ER_F16', 'R_T18', 'RE_F18', 'ET_19', 'ES_F19', 'S_T20',
       'Ss_F20', 's_T21', 'sV_F21', 'V_T22', 'VE_F22', 'E_T23', 'EM_F23',
       'M_T24', 'Ms_F24', 's_T25', 'sG_F25', 'G_T26', 'GR_F26', 'R_T28',
       'RA_F28', 'A_T29', 'AN_F29', 'N_T30', 'ND_F30', 'D_T31', 'DE_F31',
       'E_T32', 'ES_F32', 'S_T33', 'Ss_F33', 's_T34', 'sR_F34', 'R_T35',
       'RE_F35', 'E_T36', 'ES_F36', 'S_T38', 'SP_F38', 'P_T39', 'PO_F39',
       'O_T40', 'ON_F40', 'N_T41', 'NS_F41', 'S_T42', 'SA_F42', 'A_T43',
       'AB_F43', 'B_T44', 'BI_F44', 'I_T45', 'IL_F45', 'L_T46', 'LI_F46',
       'I_T47', 'ID_F47', 'D_T48', 'DA_F48', 'A_T49', 'AD_F49', 'D_T50',
       'DE_F50', 'E_T51', 'ES_F51', 'S_T51', 'CLASS'],
      dtype='object')

In [10]:
df2.columns = df1.columns
df2.head()

,t_T1,th_F1,h_T2,he_F2,e_T3,e _F3,_T4,q_F4,q_T5,qu_F5,...,k_T45,k _F45,_T46,d_F46,d_T47,do_F47,o_T48,og_F48,g_T49,CLASS
0,-0.115,-0.998,-0.131,-0.496,-0.102,-0.816,-0.064,-0.854,-0.088,-0.713,...,-0.115,-0.705,-0.138,-0.371,-0.100,-0.393,-0.108,-0.439,-0.070,3
1,-0.091,-0.493,-0.083,-0.461,-0.085,-0.404,-0.079,-0.429,-0.104,-0.349,...,-0.113,-0.345,-0.119,-0.345,-0.088,-0.349,-0.093,-0.384,-0.069,3
2,-0.092,-0.412,-0.128,-0.354,-0.074,-0.462,-0.072,-0.393,-0.092,-0.415,...,-0.145,-0.300,-0.080,-0.325,-0.120,-0.333,-0.108,-0.397,-0.076,3
3,-0.092,-0.317,-0.132,-0.341,-0.068,-0.328,-0.077,-0.352,-0.105,-0.215,...,-0.129,-0.321,-0.115,-0.237,-0.124,-0.300,-0.096,-0.341,-0.059,3
4,-0.087,-0.416,-0.101,-0.381,-0.103,-0.429,-0.080,-0.437,-0.116,-0.405,...,-0.116,-0.289,-0.080,-0.252,-0.096,-0.428,-0.084,-0.305,-0.060,3

In [15]:
df3 = pd.concat([df1, df2],ignore_index=True)
df3.head()

,t_T1,th_F1,h_T2,he_F2,e_T3,e _F3,_T4,q_F4,q_T5,qu_F5,...,k_T45,k _F45,_T46,d_F46,d_T47,do_F47,o_T48,og_F48,g_T49,CLASS
0,0.002,0.084,0.001,0.083,0.000,0.212,0.001,0.537,0.001,0.190,...,0.001,0.217,0.001,0.630,0.001,0.133,0.002,0.602,0.002,69e5f2471e0218e82d25aaab
1,0.002,0.088,0.001,0.075,0.001,0.173,0.001,0.509,0.002,0.239,...,0.001,0.103,0.001,0.499,0.002,0.177,0.001,0.444,0.001,69e5f2471e0218e82d25aaab
2,0.002,0.099,0.001,0.067,0.001,0.187,0.001,0.549,0.001,0.111,...,0.001,0.159,0.001,1.196,0.001,0.090,0.001,0.275,0.001,69e5f2471e0218e82d25aaab
3,0.002,0.108,0.001,0.098,0.001,0.152,0.001,0.369,0.002,0.149,...,0.001,0.212,0.001,0.796,0.001,0.087,0.000,0.273,0.002,69e5f2471e0218e82d25aaab
4,0.001,0.069,0.001,0.079,0.001,0.161,0.001,0.283,0.002,0.165,...,0.001,0.171,0.002,0.299,0.001,0.126,0.001,0.334,0.001,69e5f2471e0218e82d25aaab

In [16]:
df3.to_csv("bio_bio.csv", index=False)